import pandas, sys
import pandas as pd


a = pd.read_csv("/home/risana/Downloads/Signal-Processing--master/5.Py_Scripts/kushagra_lie_R.csv")
b = pd.read_csv("/home/risana/Downloads/Signal-Processing--master/5.Py_Scripts/kushagra_truth_R.csv")
c=pd.read_csv("/home/risana/Downloads/Signal-Processing--master/5.Py_Scripts/komal_lie_R.csv")
d=pd.read_csv("/home/risana/Downloads/Signal-Processing--master/5.Py_Scripts/komal_truth_R.csv")
e=pd.read_csv("/home/risana/Downloads/Signal-Processing--master/5.Py_Scripts/nirma_lie_R.csv")
f=pd.read_csv("/home/risana/Downloads/Signal-Processing--master/5.Py_Scripts/nirma_truth_R.csv")
g=pd.read_csv("/home/risana/Downloads/Signal-Processing--master/5.Py_Scripts/nisha_lie_R.csv")
h=pd.read_csv("/home/risana/Downloads/Signal-Processing--master/5.Py_Scripts/nisha_truth_R.csv")
i=pd.read_csv("/home/risana/Downloads/Signal-Processing--master/5.Py_Scripts/himani_lie_R.csv")
j=pd.read_csv("/home/risana/Downloads/Signal-Processing--master/5.Py_Scripts/himani_truth_R.csv")
k=pd.read_csv("/home/risana/Downloads/Signal-Processing--master/5.Py_Scripts/jayti_lie_R.csv")
l=pd.read_csv("/home/risana/Downloads/Signal-Processing--master/5.Py_Scripts/jayti_truth_R.csv")
m=pd.read_csv("/home/risana/Downloads/Signal-Processing--master/5.Py_Scripts/disha_lie_R.csv")
n=pd.read_csv("/home/risana/Downloads/Signal-Processing--master/5.Py_Scripts/disha_truth_R.csv")
o=pd.read_csv("/home/risana/Downloads/Signal-Processing--master/5.Py_Scripts/kaajal_lie_R.csv")
p=pd.read_csv("/home/risana/Downloads/Signal-Processing--master/5.Py_Scripts/kaajal_truth_R.csv")
q=pd.read_csv("/home/risana/Downloads/Signal-Processing--master/5.Py_Scripts/malvika_lie_R.csv")
r=pd.read_csv("/home/risana/Downloads/Signal-Processing--master/5.Py_Scripts/malvika_truth_R.csv")
s=pd.read_csv("/home/risana/Downloads/Signal-Processing--master/5.Py_Scripts/rakhi_lie_R.csv")
t=pd.read_csv("/home/risana/Downloads/Signal-Processing--master/5.Py_Scripts/rakhi_truth_R.csv")
u=pd.read_csv("/home/risana/Downloads/Signal-Processing--master/5.Py_Scripts/shubhi_lie_R.csv")
v=pd.read_csv("/home/risana/Downloads/Signal-Processing--master/5.Py_Scripts/shubhi_truth_R.csv")
w=pd.read_csv("/home/risana/Downloads/Signal-Processing--master/5.Py_Scripts/arpit_lie_R.csv")
x=pd.read_csv("/home/risana/Downloads/Signal-Processing--master/5.Py_Scripts/arpit_truth_R.csv")
y=pd.read_csv("/home/risana/Downloads/Signal-Processing--master/5.Py_Scripts/nobha_lie_R.csv")
z=pd.read_csv("/home/risana/Downloads/Signal-Processing--master/5.Py_Scripts/nobha_truth_R.csv")
ab=pd.read_csv("/home/risana/Downloads/Signal-Processing--master/5.Py_Scripts/priya_lie_R.csv")
cd=pd.read_csv("/home/risana/Downloads/Signal-Processing--master/5.Py_Scripts/priya_truth_R.csv")
ef=pd.read_csv("/home/risana/Downloads/Signal-Processing--master/5.Py_Scripts/risana_lie_R.csv")
gh=pd.read_csv("/home/risana/Downloads/Signal-Processing--master/5.Py_Scripts/risana_truth_R.csv")
merged = pd.concat([a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,ab,cd,ef,gh])

merged.to_csv('/home/risana/Downloads/Signal-Processing--master/5.Py_Scripts/result_final.csv', index=False)